-- =========================================================
-- ENGLISH TUTORING PLATFORM
-- PHYSICAL DATABASE DESIGN V1
-- PostgreSQL
-- =========================================================


-- =========================================================
-- 1. USERS
-- =========================================================

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,

    full_name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    date_of_birth DATE,

    role TEXT NOT NULL,

    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    locked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_email_canonical
        CHECK (email = lower(btrim(email))),

    CONSTRAINT ck_users_role
        CHECK (role IN (
            'STUDENT',
            'TEACHER',
            'ADMIN'
        ))
);


-- =========================================================
-- 2. REFRESH SESSIONS
-- =========================================================

CREATE TABLE public.refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    token_hash TEXT NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_refresh_sessions PRIMARY KEY (id),

    CONSTRAINT fk_refresh_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_refresh_sessions_token_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_refresh_sessions_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_refresh_sessions_user_id
    ON public.refresh_sessions(user_id);


-- =========================================================
-- 3. EMAIL VERIFICATION CREDENTIALS
-- =========================================================

CREATE TABLE public.email_verification_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    purpose TEXT NOT NULL,
    target_email TEXT NOT NULL,

    secret_hash TEXT NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_email_verification_credentials
        PRIMARY KEY (id),

    CONSTRAINT fk_email_verification_credentials_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_email_verification_credentials_secret
        UNIQUE (secret_hash),

    CONSTRAINT ck_email_verification_credentials_target_canonical
        CHECK (target_email = lower(btrim(target_email))),

    CONSTRAINT ck_email_verification_credentials_purpose
        CHECK (purpose IN (
            'INITIAL_VERIFICATION',
            'EMAIL_CHANGE'
        )),

    CONSTRAINT ck_email_verification_credentials_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_email_verification_credentials_user
    ON public.email_verification_credentials(user_id);


-- =========================================================
-- 4. PASSWORD RESET CREDENTIALS
-- =========================================================

CREATE TABLE public.password_reset_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    secret_hash TEXT NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_password_reset_credentials
        PRIMARY KEY (id),

    CONSTRAINT fk_password_reset_credentials_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_password_reset_credentials_secret
        UNIQUE (secret_hash),

    CONSTRAINT ck_password_reset_credentials_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_password_reset_credentials_user
    ON public.password_reset_credentials(user_id);


-- =========================================================
-- 5. TEACHER APPLICATIONS
-- =========================================================

CREATE TABLE public.teacher_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    teacher_id BIGINT NOT NULL,

    specialization TEXT NOT NULL,
    teaching_experience TEXT NOT NULL,
    introduction TEXT NOT NULL,

    status TEXT NOT NULL,

    submitted_at TIMESTAMPTZ NOT NULL,

    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    rejection_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_teacher_applications
        PRIMARY KEY (id),

    CONSTRAINT fk_teacher_applications_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_teacher_applications_reviewer
        FOREIGN KEY (reviewed_by)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_teacher_applications_status
        CHECK (status IN (
            'PENDING',
            'APPROVED',
            'REJECTED'
        )),

    CONSTRAINT ck_teacher_applications_review
        CHECK ((status = 'PENDING' AND reviewed_at IS NULL AND reviewed_by IS NULL AND rejection_reason IS NULL)
            OR (status IN ('APPROVED', 'REJECTED') AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL
                AND (status <> 'REJECTED' OR rejection_reason IS NOT NULL)))
);

CREATE INDEX ix_teacher_applications_teacher
    ON public.teacher_applications(teacher_id);

CREATE INDEX ix_teacher_applications_status
    ON public.teacher_applications(status);

CREATE UNIQUE INDEX uq_teacher_applications_one_pending
    ON public.teacher_applications(teacher_id)
    WHERE status = 'PENDING';


-- =========================================================
-- 6. TEACHER PROFILES
-- =========================================================

CREATE TABLE public.teacher_profiles (
    teacher_id BIGINT NOT NULL,

    avatar_path TEXT,

    specialization TEXT NOT NULL,
    teaching_experience TEXT NOT NULL,
    introduction TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_teacher_profiles
        PRIMARY KEY (teacher_id),

    CONSTRAINT fk_teacher_profiles_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT
);


-- =========================================================
-- 7. COURSE CATEGORIES
-- =========================================================

CREATE TABLE public.course_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_course_categories
        PRIMARY KEY (id),

    CONSTRAINT uq_course_categories_name
        UNIQUE (name)
);


-- =========================================================
-- 8. COURSES
-- =========================================================

CREATE TABLE public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    teacher_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    name TEXT NOT NULL,
    description TEXT NOT NULL,

    thumbnail_path TEXT,

    tuition NUMERIC(15,2) NOT NULL,
    currency TEXT NOT NULL,

    discount_percent NUMERIC(5,2),
    discount_start_at TIMESTAMPTZ,
    discount_end_at TIMESTAMPTZ,

    min_students INTEGER NOT NULL,
    max_students INTEGER NOT NULL,

    planned_start_date DATE NOT NULL,
    timezone TEXT NOT NULL,

    session_count INTEGER NOT NULL,

    meet_url TEXT,

    status TEXT NOT NULL,

    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_courses_currency
        CHECK (currency = 'VND'),

    CONSTRAINT pk_courses
        PRIMARY KEY (id),

    CONSTRAINT fk_courses_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_courses_category
        FOREIGN KEY (category_id)
        REFERENCES public.course_categories(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_courses_tuition
        CHECK (tuition >= 0 AND tuition <> 'NaN'::numeric),

    CONSTRAINT ck_courses_capacity
        CHECK (
            min_students > 0
            AND max_students >= min_students
        ),

    CONSTRAINT ck_courses_session_count
        CHECK (session_count > 0),

    CONSTRAINT ck_courses_status
        CHECK (status IN (
            'DRAFT',
            'PUBLISHED',
            'COMPLETED',
            'CANCELLED',
            'ARCHIVED'
        )),

    CONSTRAINT ck_courses_discount_percent
        CHECK (
            discount_percent IS NULL
            OR (
                discount_percent > 0
                AND discount_percent < 100
            )
        ),

    CONSTRAINT ck_courses_discount_fields
        CHECK (
            (
                discount_percent IS NULL
                AND discount_start_at IS NULL
                AND discount_end_at IS NULL
            )
            OR
            (
                discount_percent IS NOT NULL
                AND discount_start_at IS NOT NULL
                AND discount_end_at IS NOT NULL
                AND discount_start_at < discount_end_at
            )
        )
);

CREATE INDEX ix_courses_teacher_status
    ON public.courses(teacher_id, status);

CREATE INDEX ix_courses_category_status
    ON public.courses(category_id, status);


-- =========================================================
-- 9. COURSE SCHEDULE RULES
-- =========================================================

CREATE TABLE public.course_schedule_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    course_id BIGINT NOT NULL,

    day_of_week SMALLINT NOT NULL,

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_course_schedule_rules
        PRIMARY KEY (id),

    CONSTRAINT fk_course_schedule_rules_course
        FOREIGN KEY (course_id)
        REFERENCES public.courses(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_course_schedule_rules_day
        CHECK (day_of_week BETWEEN 1 AND 7),

    CONSTRAINT ck_course_schedule_rules_time
        CHECK (end_time > start_time)
);

CREATE INDEX ix_course_schedule_rules_course
    ON public.course_schedule_rules(course_id);


-- =========================================================
-- 10. SESSIONS
-- =========================================================

CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    course_id BIGINT NOT NULL,

    session_number INTEGER NOT NULL,
    title TEXT,
    content TEXT,

    scheduled_start_at TIMESTAMPTZ NOT NULL,
    scheduled_end_at TIMESTAMPTZ NOT NULL,

    status TEXT NOT NULL,

    cancellation_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_sessions
        PRIMARY KEY (id),

    CONSTRAINT fk_sessions_course
        FOREIGN KEY (course_id)
        REFERENCES public.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_sessions_number
        CHECK (session_number > 0),

    CONSTRAINT ck_sessions_time
        CHECK (
            scheduled_end_at > scheduled_start_at
        ),

    CONSTRAINT ck_sessions_status
        CHECK (
            status IN (
                'SCHEDULED',
                'CANCELLED'
            )
        ),

    CONSTRAINT uq_sessions_course_number
        UNIQUE (course_id, session_number)
);

CREATE INDEX ix_sessions_course_start
    ON public.sessions(
        course_id,
        scheduled_start_at
    );


-- =========================================================
-- 11. SESSION SCHEDULE CHANGES
-- =========================================================

CREATE TABLE public.session_schedule_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    session_id BIGINT NOT NULL,

    old_start_at TIMESTAMPTZ NOT NULL,
    old_end_at TIMESTAMPTZ NOT NULL,

    new_start_at TIMESTAMPTZ NOT NULL,
    new_end_at TIMESTAMPTZ NOT NULL,

    changed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_session_schedule_changes
        PRIMARY KEY (id),

    CONSTRAINT fk_session_schedule_changes_session
        FOREIGN KEY (session_id)
        REFERENCES public.sessions(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_session_schedule_changes_old_time
        CHECK (
            old_end_at > old_start_at
        ),

    CONSTRAINT ck_session_schedule_changes_new_time
        CHECK (
            new_end_at > new_start_at
        )
);

CREATE INDEX ix_session_schedule_changes_session
    ON public.session_schedule_changes(session_id);


-- =========================================================
-- 12. SESSION CALENDAR EVENTS
-- =========================================================

CREATE TABLE public.session_calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    session_id BIGINT NOT NULL,

    provider TEXT NOT NULL,

    external_event_id TEXT,

    sync_status TEXT NOT NULL,
    last_synced_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_session_calendar_events
        PRIMARY KEY (id),

    CONSTRAINT fk_session_calendar_events_session
        FOREIGN KEY (session_id)
        REFERENCES public.sessions(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_session_calendar_events_session_provider
        UNIQUE (session_id, provider),

    CONSTRAINT ck_session_calendar_events_provider
        CHECK (
            provider IN ('GOOGLE_CALENDAR')
        ),

    CONSTRAINT ck_session_calendar_events_status
        CHECK (
            sync_status IN (
                'PENDING',
                'SYNCED',
                'FAILED'
            )
        ),

    CONSTRAINT ck_session_calendar_events_synced
        CHECK (sync_status <> 'SYNCED' OR (external_event_id IS NOT NULL AND last_synced_at IS NOT NULL))
);

-- V1 uses one configured Calendar; its ID belongs to backend configuration.
CREATE UNIQUE INDEX uq_session_calendar_events_external
    ON public.session_calendar_events(
        provider,
        external_event_id
    )
    WHERE external_event_id IS NOT NULL;


-- =========================================================
-- 13. ENROLLMENTS
-- =========================================================

CREATE TABLE public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    status TEXT NOT NULL,

    enrolled_at TIMESTAMPTZ,
    seat_reserved_until TIMESTAMPTZ,

    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_enrollments
        PRIMARY KEY (id),

    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES public.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_enrollments_student_course
        UNIQUE (student_id, course_id),

    CONSTRAINT ck_enrollments_status
        CHECK (
            status IN (
                'PENDING',
                'ACTIVE',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

CREATE INDEX ix_enrollments_course
    ON public.enrollments(course_id);


-- =========================================================
-- 14. ASSIGNMENTS
-- =========================================================

CREATE TABLE public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    session_id BIGINT NOT NULL,

    title TEXT NOT NULL,
    description TEXT,

    max_score NUMERIC(5,2) NOT NULL,

    due_at TIMESTAMPTZ NOT NULL,

    status TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_assignments
        PRIMARY KEY (id),

    CONSTRAINT fk_assignments_session
        FOREIGN KEY (session_id)
        REFERENCES public.sessions(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_assignments_max_score
        CHECK (max_score > 0 AND max_score <> 'NaN'::numeric),

    CONSTRAINT ck_assignments_status
        CHECK (
            status IN (
                'ACTIVE',
                'CANCELLED'
            )
        )
);

CREATE INDEX ix_assignments_session
    ON public.assignments(session_id);


-- =========================================================
-- 15. ASSIGNMENT ATTACHMENTS
-- =========================================================

CREATE TABLE public.assignment_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    assignment_id BIGINT NOT NULL,

    file_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,

    content_type TEXT,

    file_size BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_assignment_attachments
        PRIMARY KEY (id),

    CONSTRAINT fk_assignment_attachments_assignment
        FOREIGN KEY (assignment_id)
        REFERENCES public.assignments(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_assignment_attachments_storage_path
        UNIQUE (storage_path),

    CONSTRAINT ck_assignment_attachments_size
        CHECK (file_size >= 0)
);

CREATE INDEX ix_assignment_attachments_assignment
    ON public.assignment_attachments(assignment_id);


-- =========================================================
-- 16. SUBMISSIONS
-- =========================================================

CREATE TABLE public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    assignment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,

    status TEXT NOT NULL,

    content TEXT,

    submitted_at TIMESTAMPTZ,

    score NUMERIC(5,2),
    teacher_feedback TEXT,

    graded_at TIMESTAMPTZ,
    graded_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_submissions
        PRIMARY KEY (id),

    CONSTRAINT fk_submissions_assignment
        FOREIGN KEY (assignment_id)
        REFERENCES public.assignments(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submissions_student
        FOREIGN KEY (student_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submissions_grader
        FOREIGN KEY (graded_by)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_submissions_assignment_student
        UNIQUE (
            assignment_id,
            student_id
        ),

    CONSTRAINT ck_submissions_status
        CHECK (
            status IN (
                'DRAFT',
                'SUBMITTED',
                'GRADED'
            )
        ),

    CONSTRAINT ck_submissions_score
        CHECK (
            score IS NULL
            OR (score >= 0 AND score <> 'NaN'::numeric)
        ),

    CONSTRAINT ck_submissions_submission_evidence
        CHECK (status NOT IN ('SUBMITTED', 'GRADED') OR submitted_at IS NOT NULL),

    CONSTRAINT ck_submissions_grading_evidence
        CHECK (status <> 'GRADED' OR (graded_at IS NOT NULL AND graded_by IS NOT NULL))
);

CREATE INDEX ix_submissions_student
    ON public.submissions(student_id);


-- =========================================================
-- 17. SUBMISSION ATTACHMENTS
-- =========================================================

CREATE TABLE public.submission_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    submission_id BIGINT NOT NULL,

    file_name TEXT NOT NULL,
    storage_path TEXT NOT NULL,

    content_type TEXT,

    file_size BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_submission_attachments
        PRIMARY KEY (id),

    CONSTRAINT fk_submission_attachments_submission
        FOREIGN KEY (submission_id)
        REFERENCES public.submissions(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_submission_attachments_storage_path
        UNIQUE (storage_path),

    CONSTRAINT ck_submission_attachments_size
        CHECK (file_size >= 0)
);

CREATE INDEX ix_submission_attachments_submission
    ON public.submission_attachments(submission_id);


-- =========================================================
-- 18. PARTICIPANT FEEDBACK
-- =========================================================

CREATE TABLE public.participant_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    enrollment_id BIGINT NOT NULL,

    rating SMALLINT NOT NULL,
    comment TEXT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_participant_feedback
        PRIMARY KEY (id),

    CONSTRAINT fk_participant_feedback_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES public.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_participant_feedback_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT ck_participant_feedback_rating
        CHECK (rating BETWEEN 1 AND 5)
);


-- =========================================================
-- 19. TEACHER PAYMENT ACCOUNTS
-- =========================================================

CREATE TABLE public.teacher_payment_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    teacher_id BIGINT NOT NULL,

    bank_code TEXT NOT NULL,
    account_number TEXT NOT NULL,
    account_holder_name TEXT NOT NULL,

    provider TEXT NOT NULL,
    status TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_teacher_payment_accounts
        PRIMARY KEY (id),

    CONSTRAINT fk_teacher_payment_accounts_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_teacher_payment_accounts_provider
        CHECK (
            provider IN ('VIETQR')
        ),

    CONSTRAINT ck_teacher_payment_accounts_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE'
            )
        )
);

CREATE INDEX ix_teacher_payment_accounts_teacher
    ON public.teacher_payment_accounts(teacher_id);

CREATE UNIQUE INDEX uq_teacher_payment_accounts_one_active
    ON public.teacher_payment_accounts(teacher_id)
    WHERE status = 'ACTIVE';


-- =========================================================
-- 20. PAYMENTS
-- =========================================================

CREATE TABLE public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    enrollment_id BIGINT NOT NULL,
    teacher_payment_account_id BIGINT NOT NULL,

    payment_code TEXT NOT NULL,

    provider TEXT NOT NULL,
    original_amount NUMERIC(15,2) NOT NULL,
    discount_amount NUMERIC(15,2) NOT NULL,
    final_amount NUMERIC(15,2) NOT NULL,

    currency TEXT NOT NULL,

    status TEXT NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_payments_currency
        CHECK (currency = 'VND'),

    CONSTRAINT pk_payments
        PRIMARY KEY (id),

    CONSTRAINT fk_payments_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES public.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_payments_teacher_account
        FOREIGN KEY (teacher_payment_account_id)
        REFERENCES public.teacher_payment_accounts(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_payments_payment_code
        UNIQUE (payment_code),

    CONSTRAINT ck_payments_provider
        CHECK (
            provider IN ('VIETQR')
        ),

    CONSTRAINT ck_payments_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'EXPIRED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_payments_amounts
        CHECK (
            original_amount <> 'NaN'::numeric
            AND discount_amount <> 'NaN'::numeric
            AND final_amount <> 'NaN'::numeric
            AND original_amount >= 0
            AND discount_amount >= 0
            AND final_amount > 0
            AND discount_amount <= original_amount
            AND final_amount =
                original_amount - discount_amount
        ),

    CONSTRAINT ck_payments_expiry
        CHECK (
            expires_at > created_at
        ),

    CONSTRAINT ck_payments_confirmation_evidence
        CHECK (status <> 'CONFIRMED' OR confirmed_at IS NOT NULL)
);

CREATE INDEX ix_payments_enrollment
    ON public.payments(enrollment_id);

CREATE INDEX ix_payments_teacher_account
    ON public.payments(teacher_payment_account_id);

CREATE UNIQUE INDEX uq_payments_one_pending_per_enrollment
    ON public.payments(enrollment_id)
    WHERE status = 'PENDING';


-- =========================================================
-- 21. PAYMENT TRANSACTIONS
-- =========================================================

CREATE TABLE public.payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    payment_id BIGINT,
    teacher_payment_account_id BIGINT,

    provider TEXT NOT NULL,
    provider_transaction_id TEXT NOT NULL,

    amount NUMERIC(15,2) NOT NULL,
    currency TEXT NOT NULL,

    transaction_at TIMESTAMPTZ NOT NULL,

    raw_reference TEXT,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT ck_payment_transactions_currency
        CHECK (currency = 'VND'),

    CONSTRAINT pk_payment_transactions
        PRIMARY KEY (id),

    CONSTRAINT fk_payment_transactions_payment
        FOREIGN KEY (payment_id)
        REFERENCES public.payments(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_payment_transactions_teacher_account
        FOREIGN KEY (teacher_payment_account_id)
        REFERENCES public.teacher_payment_accounts(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_payment_transactions_provider
        CHECK (
            provider IN ('VIETQR')
        ),

    CONSTRAINT ck_payment_transactions_amount
        CHECK (amount > 0 AND amount <> 'NaN'::numeric)
);

CREATE INDEX ix_payment_transactions_payment
    ON public.payment_transactions(payment_id);


-- =========================================================
-- 22. REFUNDS
-- =========================================================

CREATE TABLE public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    payment_id BIGINT NOT NULL,

    amount NUMERIC(15,2) NOT NULL,
    reason TEXT NOT NULL,

    status TEXT NOT NULL,

    recipient_bank_code TEXT NOT NULL,
    recipient_account_number TEXT NOT NULL,
    recipient_account_holder TEXT NOT NULL,

    proof_image_path TEXT,

    requested_at TIMESTAMPTZ NOT NULL,
    submitted_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,
    completed_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_refunds
        PRIMARY KEY (id),

    CONSTRAINT fk_refunds_payment
        FOREIGN KEY (payment_id)
        REFERENCES public.payments(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_refunds_completed_by
        FOREIGN KEY (completed_by)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_refunds_payment
        UNIQUE (payment_id),

    CONSTRAINT ck_refunds_amount
        CHECK (amount > 0 AND amount <> 'NaN'::numeric),

    CONSTRAINT ck_refunds_status
        CHECK (
            status IN (
                'PENDING',
                'SUBMITTED',
                'COMPLETED',
                'CANCELLED'
            )
        ),

    CONSTRAINT ck_refunds_submission_evidence
        CHECK (status NOT IN ('SUBMITTED', 'COMPLETED') OR (proof_image_path IS NOT NULL AND submitted_at IS NOT NULL)),

    CONSTRAINT ck_refunds_completion_evidence
        CHECK (status <> 'COMPLETED' OR (completed_at IS NOT NULL AND completed_by IS NOT NULL))
);
