-- Additive V2: Teacher certificate evidence and verification state.
-- Spring Boot supplies timestamps and PENDING on creation/replacement.
CREATE TABLE public.teacher_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    teacher_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_teacher_certificates PRIMARY KEY (id),
    CONSTRAINT fk_teacher_certificates_teacher_profile
        FOREIGN KEY (teacher_id)
        REFERENCES public.teacher_profiles(teacher_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_teacher_certificates_status
        CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED'))
);

CREATE INDEX ix_teacher_certificates_teacher
    ON public.teacher_certificates(teacher_id);

CREATE INDEX ix_teacher_certificates_status
    ON public.teacher_certificates(status);
